== The Workshop Environment You Are Using

Your workshop environment consists of several components which have been
pre-installed and are ready to use. Depending on which parts of the
workshop you’re doing, you will use one or more of:

* https://www.openshift.com/[Red Hat OpenShift]\{:target="_blank"} -
You’ll use one or more _projects_ (Kubernetes namespaces) that are your
own and are isolated from other workshop students
* https://developers.redhat.com/products/codeready-workspaces/overview[Red
Hat CodeReady Workspaces]\{:target="_blank"} - based on *Eclipse Che*,
it’s a cloud-based, in-browser IDE (similar to IntelliJ IDEA, VSCode,
Eclipse IDE). You’ve been provisioned your own personal workspace for
use with this workshop. You’ll write, test, and deploy code from here.
* https://developers.redhat.com/products/rhamt[Red Hat Application
Migration Toolkit]\{:target="_blank"} - You’ll use this to migrate an
existing application
* https://www.redhat.com/en/products/runtimes[Red Hat
Runtimes]\{:target="_blank``} - a collection of cloud-native runtimes
like Spring Boot, Node.js, and
https://quarkus.io[Quarkus]\{:target=''_blank"}
* https://www.redhat.com/en/technologies/jboss-middleware/amq[Red Hat
AMQ Streams]\{:target="_blank"} - streaming data platform based on
*Apache Kafka*
* https://access.redhat.com/products/red-hat-single-sign-on[Red Hat
SSO]\{:target="_blank"} - For authentication / authorization - based on
*Keycloak*
* Other open source projects like
https://gogs.io/[Gogs]\{:target="_blank``} (Git server that holds
application source code),
https://knative.dev[Knative]\{:target=''_blank``} (for serverless apps),
https://jenkins.io/[Jenkins]\{:target=''_blank``} and
https://cloud.google.com/tekton/[Tekton]\{:target=''_blank``} (CI/CD
pipelines), https://prometheus.io[Prometheus]\{:target=''_blank``} and
https://grafana.com[Grafana]\{:target=''_blank"} (monitoring apps), and
more.

You’ll be provided clickable URLs throughout the workshop to access the
services that have been installed for you.

== How to complete this workshop

Simply follow these instructions end-to-end. *You’ll need to do quite a
bit of copy/paste for Linux commands and source code modifications*, as
well as clicking around on various consoles used in the labs. When you
get to the end of each section, you can click the ``Next >'' button at
the bottom to advance to the next topic. You can also use the menu on
the left to move around the instructions at will.

The entire workshop is split into one or more _modules_ - Look at the
top of the screen in the header to see which module you are on. After
you complete this module, your instructor may have additional modules to
complete.

Good luck, and let’s get started!
